### ISSUE TITLE
Tensorboard Implementation and output

### ISSUE THREAD

**Issue by pravzK94** [bowang-lab/BIONIC#21]
I have been trying to implement tensorboard for more detailed analysis and visualization.  For which, I have mentioned 'use_tensorboard': true in the json file and I am unable to acquire any logfiles or relevant output files. Currently, tensorflow-tensorboard is installed by conda environment in my system. I request to mention the proper procedure to implement the same.

**Comment by duncster94** [comment]
Hi, thanks for opening an issue. The tensorboard integration does not work in the current release - I should have updated the documentation to reflect that. If you give me a few days I can look into integrating tensorboard in the latest version and push a new release.

**Comment by pravzK94** [comment]
I am currently working with latest release v0.2.1 and definitely looking forward for tensorboard integration as it is crucial for our work. Please, do update on new release with tensorboard integration. Looking forward for the same.

**Comment by duncster94** [comment]
Hi @EvilScience94, I've released [version 0.2.2](https://github.com/bowang-lab/BIONIC/releases/tag/v0.2.2) which has TensorBoard support. The README has been updated to reflect the config file changes and instructions have been added on how to run TensorBoard.

Please let me know if this works for you, and if you have any questions.

**Comment by pravzK94** [comment]
Hi, very thankful for quick update. I did install latest version 0.2.2 and executed a run with my files, but still couldn't obtain logdir files for tensorboard. I am attaching the 
[MycoCd34.txt](https://github.com/bowang-lab/BIONIC/files/7887548/MycoCd34.txt)
config file for your perusal. Please, look into it let me know where I am doing it wrong.

**Comment by duncster94** [comment]
Thanks for trying out the latest version. Your `tensorboard.log_dir` key should be nested, and you should also specify whether you want the training metrics (`training`) and/or embedding projector (`embedding`) to be recorded. Your config would look like:

```
{
    ...
    "tensorboard": {
        "training": true,
        "embedding": true,
        "log_dir": "runs/Cd3401"
    }
}
```

Let me know if that helps.

**Comment by pravzK94** [comment]
It did work this time. I am able to acquire the tensors, metadata tsv files and config file for tensorboard. thank you very much for prompt help.

**Comment by duncster94** [comment]
Great! Glad to hear it worked. I'll close the issue but feel free to open it again if you run into any issues.
