### ISSUE TITLE
BIONIC for MacOS?

### ISSUE THREAD

**Issue by SaharAlkh** [bowang-lab/BIONIC#25]
Hi

I would like to try out BIONIC on MacOS ver 12.0.1. 

I understand that the installation wheels are for windows or linux and that it requires CUDA which is not available for MacOS.  Is there a way to install and run BIONIC on MacOS? I am having trouble installing CUDA and Pytorch that BIONIC requires.

Thanks

**Comment by duncster94** [comment]
Hi, thanks for opening an issue. To my knowledge, CUDA is not available on macOS, and this is reflected in the underlying PyTorch Geometric package as well (see [here](https://github.com/pyg-team/pytorch_geometric#pip-wheels)). There is a CPU version of PyTorch Geometric available for macOS however, so I could build a CPU capable version of BIONIC that runs on macOS. Note that GPU support is highly recommended for the substantial speedup in training and inference, though if you're running BIONIC on a small number of small networks (say 1000 nodes or less), CPU only might be sufficient.

If you're okay with a CPU only version I can build and release a wheel for macOS - how does that sound?

**Comment by SaharAlkh** [comment]
A CPU only version that works for macOS sounds great!
Thank you

**Comment by duncster94** [comment]
So I looked into this and the latest available version for macOS is 10.15. I think this will work on 12.0.1 but you'll have to test it yourself. I built a `.whl` file for BIONIC on macOS 10.15. You can download the [artifact.zip](https://github.com/bowang-lab/BIONIC/files/7981127/artifact.zip) file, extract the `.whl` file and try installing it by following [these instructions](https://github.com/bowang-lab/BIONIC#installing-from-wheel-recommended-for-general-use).

Please let me know if this works on your system so I know if I can officially release it.

**Comment by SaharAlkh** [comment]
Thank you Duncan.

I tried installing BIONIC on my MacOS ver 12.0.1 using Python 3.8.12 from
the wheel you just created and am getting an error message.

pip install bionic_model-0.2.2+cpu-cp38-cp38-macosx_10_14.whl

ERROR: bionic_model-0.2.2+cpu-cp38-cp38-macosx_10_14.whl is not a supported
wheel on this platform.


Am I missing something?


Best,

Sahar

**Comment by duncster94** [comment]
Hmm, I'm not entirely sure. Does your device use an Intel or M1 chip?

Can you try changing the `10_14` in the wheel file name to `10_9` and trying to install it again?

If the wheel installation doesn't work, I'd recommend you try the [poetry installation](https://github.com/bowang-lab/BIONIC#installing-using-poetry-recommended-for-development) approach.

**Comment by SaharAlkh** [comment]
Changing the wheel name didn't work.

I did follow the poetry installation instructions  using the following:


pip install torch==1.9.0 -f
https://download.pytorch.org/whl/torch_stable.html


pip install torch-scatter==2.0.8 torch-sparse==0.6.11 torch-cluster==1.5.9
-f https://pytorch-geometric.com/whl/torch-1.9.0+cpu.html


It is running now on my mac.


Thanks for your help.

**Comment by duncster94** [comment]
Okay, thanks for attempting the wheel installation. I'll close this issue for now.
