### ISSUE TITLE
supported wheel installation

### ISSUE THREAD

**Issue by raminass** [bowang-lab/BIONIC#30]
trying to install using wheel on Google Colab, however couldn't find a supported wheel version:
ERROR: bionic_model-0.2.1+cu102-cp37-cp37-linux_x86_64.whl is not a supported wheel on this platform.

Also tried the installation using Poetry, and passing poetry install successfully, still can't find bionic command.  please advise!

**Comment by duncster94** [comment]
Hi, apologies for the late reply and thanks for opening an issue.

I'm not too familiar with Google Colab - can you find out what operating system your notebook is using (platform and version)?

For the Poetry issue, make sure you've added Poetry to your `PATH`, see [here](https://python-poetry.org/docs/#installation). If that doesn't work you can also try adding your environment to `PYTHONPATH` like so:

    $ export PYTHONPATH=$HOME/path/to/env/nameofenv:$PYTHONPATH

Let me know if that works, if not we can debug further.

**Comment by duncster94** [comment]
I'm going to close this issue due to staleness, feel free to reopen it if you want to.

**Comment by lioninjia** [comment]
Hello, I have a similar issue. I am trying to execute the following command
`pip install https://github.com/bowang-lab/BIONIC/releases/download/v0.2.6/bionic_model-0.2.6+cpu-cp38-cp38-win_amd64.whl`

However, I get the next error
`ERROR: bionic_model-0.2.6+cpu-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.`

I have pip 23.1 version, Python 3.10 version and using 64-bit Windows 10 and Intel(R) Core(TM) i7-7700HQ CPU processor
I don't understand what I'm doing wrong

**Comment by duncster94** [comment]
Hi, you need to be using Python 3.8 otherwise some dependencies will not work.
