### ISSUE TITLE
How do I get the right "cu version"?

### ISSUE THREAD

**Issue by mr-september** [bowang-lab/BIONIC#4]
From the Readme:
```
Make sure your virtual environment is active, then install BIONIC by running

$ pip install bionic_model==${VERSION}+${CUDA} -f https://bowang-lab.github.io/BIONIC/wheels.html
where ${VERSION} is the version of BIONIC you want to install (currently 0.1.0) and ${CUDA} is one of cpu, cu92, cu101, cu102, corresponding to the CPU, CUDA 9.2, CUDA 10.1 and CUDA 10.2 versions, respectively. Note, as above, that cu92 is not available on Windows.
```
When googling (on Ubuntu 20.10), the answer seems to be `nvcc --version`
which returns
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```
which doesn't seem to match any of the above examples, spanning `92` to `102`? seems like `cu110` would be the equivalent for my system, but that returns
```
ERROR: Could not find a version that satisfies the requirement bionic_model==0.1.0+cu110
ERROR: No matching distribution found for bionic_model==0.1.0+cu110
```

In fact, reverting to the `cu102` yields the same error:
```
ERROR: Could not find a version that satisfies the requirement bionic_model==0.1.0+cu102
ERROR: No matching distribution found for bionic_model==0.1.0+cu102
```
Is my formatting wrong?

**Comment by duncster94** [comment]
Hi, currently BIONIC doesn't support CUDA 11.0. You have two options:

1. Downgrade your system's CUDA version to one of the supported CUDA versions, or
2. Do the [Poetry](https://github.com/bowang-lab/BIONIC#installing-using-poetry) installation. Here you would need to change the PyTorch version to 1.7.0, and install the correct PyTorch Geometric dependencies (`torch-cluster`, `torch-scatter`, `torch-sparse`) from [here](https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html) and then `pip install torch-geometric`. Unfortunately, PyTorch Geometric introduces breaking changes with most releases, so you'd likely run into errors with the `GATConv` layer when trying to run BIONIC (which I'd be happy to help you fix).

I highly recommend option 1 if you don't specifically need CUDA 11.0. Otherwise, you'd have to try option 2. I can guide you along the way if you run into trouble.

**Comment by mr-september** [comment]
Thanks. I will try 1. But just to clarify, is
```
pip install bionic_model==0.1.0+cu102 -f https://bowang-lab.github.io/BIONIC/wheels.html
```
returning
```
ERROR: Could not find a version that satisfies the requirement bionic_model==0.1.0+cu102
ERROR: No matching distribution found for bionic_model==0.1.0+cu102
```
a problem from the incompatibility, or from me entering the install command wrongly?

**Comment by duncster94** [comment]
Hmm, I'm not entirely sure why that's happening. Thanks for the heads up!

You should be able to install the wheel by **downloading it locally**, then running `pip install bionic_model-0.1.0+cu102-cp38-cp38-linux_x86_64.whl` in the same directory as the wheel file.

One other suggestion, if you don't have large networks to integrate you can also try the CPU version of BIONIC, (i.e. `pip install bionic_model-0.1.0+cpu-cp38-cp38-linux_x86_64.whl`). This avoids any issues with CUDA in the first place.

**Comment by mr-september** [comment]
Just wondering, what's your ballpark threshold for a "large" network? >100 nodes?

**Comment by duncster94** [comment]
Around >500 nodes the CPU version will start to struggle, though this is also related to network density (sparser networks run faster). How big are your networks/how many networks do you have?

**Comment by mr-september** [comment]
I'll be using this on a bunch of small-ish networks, ~10-50 nodes each, so CPU-only should be just fine for now.

Regarding the install, though, it appears to go successfully, but verifying with `bionic --help` returns
```
Traceback (most recent call last):
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/bin/bionic", line 5, in <module>
    from bionic.cli import main
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/bionic/cli.py", line 4, in <module>
    from .train import Trainer
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/bionic/train.py", line 16, in <module>
    from .utils.preprocessor import Preprocessor
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/bionic/utils/preprocessor.py", line 14, in <module>
    from torch_geometric.transforms import ToSparseTensor
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/torch_sparse/__init__.py", line 12, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/media/september/6A68A60268A5CCDF/Git/Annotation-dev/Python/BIONIC38/venv/lib/python3.8/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```
I'm on Ubuntu 20.10, and using PyCharm IDE. Do you know where I should look to troubleshoot this?

**Comment by duncster94** [comment]
This looks like an error with CUDA. Which BIONIC wheel did you install? If you install the CPU wheel (i.e. `bionic_model-0.1.0+cpu-cp38-cp38-linux_x86_64.whl`) then you shouldn't run into this problem.

I'm guessing you installed the CUDA 10.2 wheel, is that correct? If so you would need to downgrade your current CUDA 11.0 version to 10.2 to get this to work, or you can uninstall BIONIC and reinstall with the CPU wheel which doesn't care about your CUDA version.

Does that help?

EDIT: [This](https://github.com/rusty1s/pytorch_geometric/issues/114) is a relevant issue as well.

**Comment by mr-september** [comment]
Hmm yes, I installed the cuda10.2 wheel, then later installed the cpu wheel, i think there were conflicts.

This was resolved with
```
pip install --upgrade --force-reinstall bionic_model-0.1.0+cpu-cp38-cp38-linux_x86_6.whl
```

bionic --help is working now. Thanks!
