### ISSUE TITLE
 Save reconstruction loss for each feature as .txt

### ISSUE THREAD

**Issue by SaharAlkh** [bowang-lab/BIONIC#40]
Hi,
Would it be possible to add an option to save the reconstruction loss for each feature as .txt. That would help for further downstream analyses.
Thanks

**Comment by duncster94** [comment]
Hi, can you elaborate on what you mean by "reconstruction loss for each feature"?

**Comment by SaharAlkh** [comment]
What I mean is to save the reconstruction loss values for each input
network. It would be the same information that was used to plot the loss
curves but just as a text file.

**Comment by duncster94** [comment]
Hi, if you want the reconstruction loss for each network across all epochs you can add the following to [`plotter.py`](https://github.com/bowang-lab/BIONIC/blob/master/bionic/utils/plotter.py) on line 29:

    import pandas as pd

    data = pd.DataFrame(train_losses[: len(net_names)], index=net_names, columns=x_epochs).T
    data.to_csv("path/to/output.tsv", sep="\t")

**Comment by SaharAlkh** [comment]
Great. Thank you for your help
