### ISSUE TITLE
Large network data integration

### ISSUE THREAD

**Issue by zhanlingm** [bowang-lab/BIONIC#44]
Hello, Doctor! I have learned a lot from your article recently, which just solved the problem I encountered. However, there is still a problem. When I used the bionic method to deal with a large network, the processing effort was extremely long. Of course I use the CPU processing, so want to consult, for the large network should be how to deal with, how the computer configuration?

Thank you so much!

**Comment by duncster94** [comment]
Hi, thanks for opening an issue. What version of BIONIC are you using? I recently released [v0.2.5](https://github.com/bowang-lab/BIONIC/releases/tag/v0.2.5) which significantly improves the network preprocessing.

**Comment by zhanlingm** [comment]
Hi, thank you for taking time out of your busy schedule to reply to my message. I am using bionic v0.2.5. When I used bionic to run pathway data (11167 nodes and 100,000 relationship edges), the total time was 108 days. Is it because of my CPU configuration?

> Hi, thanks for opening an issue. What version of BIONIC are you using? I recently released [v0.2.5](https://github.com/bowang-lab/BIONIC/releases/tag/v0.2.5) which significantly improves the network preprocessing.

**Comment by duncster94** [comment]
Hi, it sounds like the training is what's taking a long time. Yes, the CPU version is only suitable for small networks. I recommend you install a CUDA version and run BIONIC on a GPU.

**Comment by zhanlingm** [comment]
> Hi, it sounds like the training is what's taking a long time. Yes, the CPU version is only suitable for small networks. I recommend you install a CUDA version and run BIONIC on a GPU.

hi, thank you for your patience and guidance. I got a lot of help. Thank you again!

**Comment by duncster94** [comment]
No problem! I'll close this issue but if you run into problems feel free to reopen it or open a new one.
