### ISSUE TITLE
Directed networks?

### ISSUE THREAD

**Issue by mr-september** [bowang-lab/BIONIC#5]
Saw this in the readme: 

> BIONIC assumes all networks are undirected and enforces this in its preprocessing step.

Unfortunate, considering that regulatory networks are directed.

Is there anything inherent in the methods that prevents "using" directed nodes properly?

**Comment by duncster94** [comment]
Unfortunately this is a limitation of the underlying GNN library PyTorch Geometric (see [here](https://github.com/rusty1s/pytorch_geometric/issues/2092#issuecomment-774981466)). Integrating undirected graphs might still be appropriate, however. What's the end goal?

**Comment by mr-september** [comment]
Thanks. Looking at that issue, wouldn't it be better to write BIONIC around directed as the base/default case, with an optional parameter to specify undirected input files? Or even vice versa, in the backend? Seems easy to write a function to internally mirror/"double up" undirected input files.

If this were the case, it would be more clear-cut that BIONIC is superior to MashUp, rather than being situationally better.

**Comment by duncster94** [comment]
I'm not sure I understand. PyTorch Geometric cannot handle directed networks (it just transforms directed networks to undirected), so other than designing a new graph neural network architecture that specifically handles directed networks, BIONIC also can only handle undirected networks.

While you can certainly input directed networks into BIONIC, as I mentioned, these are just converted to undirected networks.
