### ISSUE TITLE
Would there be a version of pytorch 1.13 and python 3.10?

### ISSUE THREAD

**Issue by deweihu96** [bowang-lab/BIONIC#50]
Would there be a version of pytorch 1.13 and python 3.10?

**Comment by duncster94** [comment]
Hi, thanks for opening an issue. Unfortunately there isn't a version of BIONIC compatible with PyTorch 1.13. This would involve updating PyTorch Geometric which introduced a number of breaking changes between version 1.7 and version 2.0 so I'd have to update the BIONIC codebase as well. I'll mark this issue as a feature request and see about updating BIONIC to the latest PyTorch and PyTorch Geometric version for the next release.

**Comment by deweihu96** [comment]
> Hi, thanks for opening an issue. Unfortunately there isn't a version of BIONIC compatible with PyTorch 1.13. This would involve updating PyTorch Geometric which introduced a number of breaking changes between version 1.7 and version 2.0 so I'd have to update the BIONIC codebase as well. I'll mark this issue as a feature request and see about updating BIONIC to the latest PyTorch and PyTorch Geometric version for the next release.

Hi @duncster94 , thank you for your fast reply and all the work done in BIONIC! After some trials with my teammates, we found the environment as follow could also work: 
In Linux system, 
```
python==3.8
torch==1.13 with cuda
torch-geometric==1.7.2
latest torch-scatter torch-sparse torch-cluster
```
and finally, install BIONIC inside the repo, with `poetry install`.

Hope it also helps other people.
