### ISSUE TITLE
Using differential expression and/or MOFA output as input

### ISSUE THREAD

**Issue by ZainulArifin1** [bowang-lab/BIONIC#58]
Thank you for the tools. I currently have a resolved network (constructed from kinase and TF activity), coexpression network (one from transcriptomics, one from proteomics), and ground truth interactions from Omnipath. I also have output from MOFA (linear factorization integration method) and typical differential expression/abundance. 

As we are interested to study the signaling of a specific gene and identify novel interaction in relation to that gene, can we also use the MOFA or DEG output as input for Bioinic?

Thank you.

**Comment by duncster94** [comment]
Hi, thanks for your interest in BIONIC.

As long as you convert your inputs into networks (i.e. by computing pairwise similarity and thresholding to get edges), you can use these with BIONIC.

**Comment by ZainulArifin1** [comment]
Noted. I think I can input these results into string and use string output as input. Many thanks for the prompt reply.
