### ISSUE TITLE
installation issue: wheel not supported

### ISSUE THREAD

**Issue by ssyang3** [bowang-lab/BIONIC#59]
Hi:  By running "pip install https://github.com/bowang-lab/BIONIC/releases/download/v0.2.6/bionic_model-0.2.6+cpu-cp38-cp38-linux_x86_64.whl", I got "ERROR: bionic_model-0.2.6+cpu-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform", using pip version 19.3.1 as suggested in [READM.md](https://github.com/bowang-lab/BIONIC/commit/807aadbeb18eb367dc31b3dfa4e6b0638897bfe3) (line 71).  The same error message with the 'cu102' and 'cu11' versions as listed in https://github.com/bowang-lab/BIONIC/releases.  I am very new to this field and would greatly appreciate your help in navigating through the installation steps.

**Comment by duncster94** [comment]
Hi, thanks for opening an issue.

What operating system are you using? Linux? What is the distribution?

**Comment by ssyang3** [comment]
Ubuntu 22.04.3 LTS.  Thanks.

**Comment by duncster94** [comment]
Thanks, are you using Python 3.8? If you're having trouble with the wheel installation then you should try the Poetry installation. Let me know if you have any issues.

**Comment by ssyang3** [comment]
No.  I was using Python 10.x.  I just recreated a virtual environment using Python 3.8.  Now It is working fine.  Thank you so much!

**Comment by duncster94** [comment]
Great, thanks!
